declare type ApiKey = baseApiKey | exhibitApiKey | authApiKey | identityVerificationApiKey
				| searchEngineApiKey | shoppingApiKey | rankingApiKey | goodsApiKey
				| globalConfigApiKey | renewalApiKey | csApiKey | memberApiKey
				| myOrderApiKey | orderApiKey | nativeAppApisKey | thirdPartyApiKey | liveCommerceApiss;

type baseApiKey = 'USER_INFO' | 'SHOPPER_UUID' | 'SEARCH_ADDRESS' | 'ADDRESS_EXTRA_AREA_CHECK'
				| 'REGIST_POLICIES' | 'BRAND_CATEGORIES' | 'ALL_DISPLAY_BRANDS' | 'POLICY_NOW_DISPLAY_END_PREV_LIST'
				| 'USER_GRADE_COLORS' | 'POLICY_DETAIL' | 'PARTNERSHIP_INQUIRY_CATEGORIES' | 'PARTNERSHIP_INQUIRY_TYPES'
				| 'SEND_PARTNERSHIP_INQUIRY' | 'BLOCK_PAGE' | 'BLOCK_BLOCK' | 'COMPANY_LIST';

/** 이벤트, 프로모션, 기획전 등 */
type exhibitApiKey = 'FETCH_BASE_SEARCH_WORDS' | 'FETCH_MAIN_BANNERS' | 'FETCH_MAIN_POPUPS' | 'TIME_DEAL'
				| 'CARD_INSTALLMENT' | 'EXH_PLANNING_DETAIL' | 'EXH_PLANNING_COMMENTS' | 'CREATE_EXH_PLANNING_COMMENT'
				| 'UPDATE_EXH_PLANNING_COMMENT' | 'DELETE_EXH_PLANNING_COMMENT' | 'EXH_PLANNING_GROUP_GOODS' | 'SHOWCASE_SORT_LIST'
				| 'SHOWCASE_LIST' | 'SHOWCASE_DETAIL' | 'ANOTHER_SHOWCASE_LIST' | 'CODY_SHOT_CATEGORIES'
				| 'CODY_SHOT_DETAIL' | 'MAIN_CODY_SHOTS' | 'MAIN_RECENT_CODY_SHOTS' | 'MAIN_SPECIAL_EVENTS'
				| 'SPECIAL_EVENT_DETAIL' | 'SPECIAL_EVENT_GROUP_GOODS' | 'SPECIAL_EVENT_COMMENTS' | 'CREATE_SPECIAL_EVENT_COMMENT'
				| 'DELETE_SPECIAL_EVENT_COMMENT' | 'UPDATE_SPECIAL_EVENT_REVIEW_COMMENT' | 'EXPERIENCEGROUP_REVIEW_LIST' | 'EXPERIENCEGROUP_REVIEWABLE_GOODS'
				| 'EXPERIENCEGROUP_REVIEW_STORE' | 'EXPERIENCEGROUP_REVIEW_RECOMMENDATION' | 'EXPERIENCEGROUP_REVIEW_RECOMMENDATION_ADD' | 'EXPERIENCEGROUP_REVIEW_RECOMMENDATION_CANCEL'
				| 'EXPERIENCEGROUP_REVIEW_DETAILS' | 'JOINT_PURCHASE_LIST' | 'JOINT_PURCHASE_DETAIL' | 'JOINT_PURCHASE_APPLY'
				| 'MAIN_RAFFLES' | 'RAFFLES_ENDED' | 'RAFFLE_ENTRY' | 'RAFFLE_WINNERS'
				| 'RAFFLE_ENTRY_INFO' | 'RAFFLE_WINNING_RESULT' | 'RAFFLE_IS_BUYABLE_CHECK';

/** 계정 */
type authApiKey = 'AUTH_LOGIN' | 'AUTH_LOGOUT' | 'AUTH_REFRESH' | 'AUTH_ME'
				| 'AUTH_GUEST_LOGIN' | 'AUTH_FIND_ID' | 'AUTH_FIND_PASSWORD' | 'AUTH_SEND_VERIFICATION_CODE_EMAIL'
				| 'AUTH_SEND_VERIFICATION_CODE_PHONE' | 'AUTH_VERIFY_CODE' | 'AUTH_CHANGE_PASSWORD' | 'AUTH_SEND_UNMASKED_ID_EMAIL'
				| 'AUTH_SEND_UNMASKED_ID_PHONE' | 'AUTH_ID_DUPLICATE_CHECK' | 'AUTH_USER_REGIST' | 'AUTH_TOKEN_DUPLICATE_CHECK'
				| 'AUTH_REFRESH_TOKEN' | 'AUTH_CAPTCHA_IMAGE' | 'AUTH_CAPTCHA_CERTIFICATE' | 'AUTH_PASSWORD_ADVICE_CHANGE'
				| 'AUTH_IDENTITY_VERIFICATION_CONFIRM';

/** 본인인증 */
type identityVerificationApiKey = 'IDENTITY_VERIFICATION_GENERATE_TOKEN' | 'IDENTITY_VERIFICATION_RESULT';

/** 검색엔진 */
type searchEngineApiKey = 'SEARCH_ENGINE_HOT_SEARCHES' | 'SEARCH_ENGINE_AUTO_COMPLETE' | 'SEARCH_ENGINE_SEARCH' | 'SEARCH_ENGINE_FEEDBACK';

/** 쇼핑 */
type shoppingApiKey = 'SHOPPING_ADD_CART_GOODS' | 'SHOPPING_CART_ITEMS' | 'SHOPPING_FETCH_LIKED_GOODS' | 'SHOPPING_CART_ITEMS_REMOVE'
				| 'SHOPPING_CART_ITEM_OPTION_AND_STOCK_UPDATE' | 'SHOPPING_CART_COUNT' | 'SHOPPING_WISH_BRANDS' | 'SHOPPING_GIVEAWAY_DETAIL'
				| 'SHOPPING_GIVEAWAY_DETAIL_TARGET_GOODS';

/** 랭킹 */
type rankingApiKey = 'RANKING_ITEM' | 'RANKING_BRAND';

/** 상품 */
type goodsApiKey = 'GOODS_DISPLAY_ALL_CATEGORIES' | 'GOODS_CATEGORIES_INCLUDE_COUNT' | 'GOODS_DETAIL_REVIEWS' | 'GOODS_DETAIL_REVIEW_STATS'
				| 'GOODS_DETAIL_PHOTO_REVIEW_DETAIL' | 'FETCH_MAIN_CATEGORY_BEST_GOODS' | 'GOODS_DETAIL_PACKAGES' | 'GOODS_DETAIL_BRAND_BEST_GOODS'
				| 'GOODS_DETAIL_MAIN_CATEGORY_BEST_GOODS' | 'GOODS_DETAIL_BASIC_INFO' | 'GOODS_DETAIL_INFORMATION' | 'GOODS_DETAIL_QNA_LIST'
				| 'GOODS_DETAIL_QNA_WRITE_INFO' | 'GOODS_STORE_QNA' | 'GOODS_UPDATE_QNA' | 'GOODS_DESTROY_QNA'
				| 'GOODS_SHOW_QNA' | 'GOODS_DETAIL_DOWNLOADABLE_COUPONS' | 'GOODS_DETAIL_COUPON_DOWNLOAD' | 'GOODS_PHOTO_REVIEWS'
				| 'GOODS_DETAIL_PROMOTIONS' | 'GOODS_OPTIONS' | 'GOODS_EP_COUPON' | 'GOODS_DETAIL_AGGREGATE'
				| 'GOODS_DETAIL_STOCK' | 'GOODS_DETAIL_BEST_REVIEWS' | 'GOODS_DETAIL_BEST_REVIEW' | 'GOODS_REVIEW_ZOOM_IMAGES'
				| 'GOODS_DETAIL_ME' | 'GOODS_CATEGORIES_COMMON' | 'GOODS_CATEGORIES_FILTER' | 'GOODS_CATEGORIES_COMMON_COUNT'
				| 'GOODS_CATEGORIES_COMMON_INFO' | 'GOODS_BRAND_SHOP_INFO_WITH_CURATION' | 'GOODS_BRAND_SHOP_FILTERED_GOODS' | 'GOODS_BRAND_SHOP_COUNT'
				| 'GOODS_BRAND_SHOP_FILTER' | 'GOODS_SIZE_GUIDE' | 'GOODS_SELLER_SHOP_INFO' | 'GOODS_SELLER_SHOP_CURATION'
				| 'GOODS_SELLER_SHOP_FILTER' | 'GOODS_SELLER_SHOP_GOODS_COUNT' | 'GOODS_SELLER_SHOP_FILTERED_GOODS' | 'GOODS_RESTOCK_NOTIFY_APPLY'
				| 'GOODS_RAFFLE_DETAIL' | 'GOODS_TIME_ATTACK_DETAIL';

/** 설정 */
type globalConfigApiKey = 'CONF_SHOP_INFORMATION' | 'CONF_BANK_CODES' | 'CONF_POINT_RULE' | 'CONF_POINT_LABEL'
				| 'CONF_GRADE_REVIEW_POINT_SETTING' | 'CONF_SHOES_SIZE' | 'CONF_CANCEL_REASONS' | 'CONF_RETURN_REASONS'
				| 'CONF_EXCHANGE_REASONS' | 'CONF_DELIVERY_COMPANIES' | 'CONF_SHOES_CATEGORIES' | 'CONF_FIT_LIST'
				| 'CONF_CLAIM_REWARD_INFO' | 'CONF_INITIAL_SETTINGS';

/** 리뉴얼 */
type renewalApiKey = 'RENEWAL_CHECK_EXIST_USER' | 'RENEWAL_PASSWORD_CHANGE';

/** 고객센터 */
type csApiKey = 'CS_GRADE_BENEFIT_INFO' | 'CS_QNA_TYPES' | 'CS_SELLER_QNA_TYPES' | 'CS_FAQ_TYPES'
				| 'CS_FAQ_LIST' | 'CS_FAQ_ALL_LIST' | 'CS_TOP_NOTICES' | 'CS_NOTICE_LIST'
				| 'CS_IMPORTANT_NOTICES' | 'CS_NOTICE' | 'CS_SHOPPING_GUIDES_ACTIVES_INFORMATION';

/** 회원 마이페이지 */
type memberApiKey = 'MEMBER_CONNECTED_SOCIALS' | 'MEMBER_EDIT_INFO' | 'MEMBER_UPDATE_INFO' | 'MEMBER_UPDATE_REVIEW'
				| 'MEMBER_REVIEW' | 'MEMBER_STORE_REVIEW' | 'MEMBER_REVIEWS' | 'MEMBER_CHANGE_PASSWORD'
				| 'MEMBER_CHECK_DUPLICATE_EMAIL' | 'MEMBER_WITHDRAW_REASONS' | 'MEMBER_WITHDRAW' | 'MEMBER_PREPARE_FOR_EDIT'
				| 'MEMBER_CHECK_CURRENT_PASSWORD' | 'MEMBER_COUPON_REGIST_LIST' | 'MEMBER_COUPON_REGIST' | 'MEMBER_COUPON_USABLE_GOODS'
				| 'MEMBER_COUPON_USABLE_BRANDS' | 'MEMBER_REGIST_COUPON' | 'MEMBER_POINT_HISTORY' | 'MEMBER_REFUND_ACCOUNT'
				| 'MEMBER_CREATE_OR_UPDATE_REFUND_ACCOUNT' | 'MEMBER_DELETE_REFUND_ACCOUNT' | 'MEMBER_WISH_BRANDS' | 'MEMBER_WISH_ALL_BRANDS'
				| 'MEMBER_STORE_WISH_BRAND' | 'MEMBER_DELETE_WISH_BRAND' | 'MEMBER_WISH_GOODS_FOLDERS' | 'MEMBER_WISH_GOODS'
				| 'MEMBER_WISH_GOODS_IN_FOLDER' | 'MEMBER_DELETE_WISH_GOODS' | 'MEMBER_CREATE_WISH_FOLDER' | 'MEMBER_UPDATE_WISH_FOLDER'
				| 'MEMBER_UPDATE_WISH_GOODS_FOLDER_SORT' | 'MEMBER_DELETE_WISH_GOODS_FOLDER' | 'MEMBER_STORE_WISH_GOODS' | 'MEMBER_UPDATE_WISH_GOODS'
				| 'MEMBER_RECENT_VIEW_GOODS' | 'MEMBER_ADD_RECENT_VIEW_GOODS' | 'MEMBER_RECENT_VIEW_PLANNINGS' | 'MEMBER_ADD_RECENT_VIEW_PLANNING'
				| 'MEMBER_AGGREGATES_BENEFIT' | 'MEMBER_AGGREGATES_ORDER' | 'MEMBER_AGGREGATES_GRADEUP_CONDITION' | 'MEMBER_SELLER_QNA_LIST'
				| 'MEMBER_PREPARE_FOR_EDIT_SOCIAL' | 'MEMBER_REVIEW_WRITABLES' | 'MEMBER_REVIEW_TEMPLATES' | 'MEMBER_STORE_QNA'
				| 'MYPAGE_QNA_LIST' | 'MEMBER_QNA' | 'MEMBER_UPDATE_QNA' | 'MEMBER_DELETE_QNA'
				| 'MEMBER_QNA_ORDERS' | 'MEMBER_AGGREGATES_REVIEW' | 'MEMBER_GRADE_COUPON_REGIST_COUNT' | 'MEMBER_DOWNLOAD_GRADE_COUPON'
				| 'MEMBER_RECEIVE_ADDRESS' | 'MEMBER_STORE_RECEIVE_ADDRESS' | 'MEMBER_DELETE_RECEIVE_ADDRESS' | 'MEMBER_DELETE_SELLER_QNA'
				| 'MEMBER_SELLER_QNA_WRITABLE_ORDER_ITEMS' | 'MEMBER_STORE_SELLER_QNA' | 'MEMBER_SELLER_QNA' | 'MEMBER_UPDATE_SELLER_QNA'
				| 'MEMBER_ADULT_VERIFICATIONS' | 'MEMBER_MY_SIZE' | 'MEMBER_MY_SIZE_UPDATE' | 'MEMBER_CLAIM_DELIVERY_DELAY_REPORTABLE_ORDER_ITEMS'
				| 'MEMBER_CLAIM_REPORT_DELIVERY_DELAY_ORDER_ITEMS' | 'MEMBER_CLAIM_DELIVERY_DELAY_REPORTED_ORDER_ITEMS' | 'MEMBER_CLAIM_SOLDOUT_CANCEL_REPORTABLE_ORDER_ITEMS' | 'MEMBER_CLAIM_SOLDOUT_CANCEL_REPORTED_ORDER_ITEMS'
				| 'MEMBER_CLAIM_REPORT_SOLDOUT_CANCEL_ORDER_ITEMS' | 'MYPAGE_RAFFLE_ENTRY_LIST';

/** 마이페이지 주문 */
type myOrderApiKey = 'MEMBER_ORDER_LIST' | 'MEMBER_ORDER_STATUS_CODES' | 'ORDER_CONFIRM_PURCHASE' | 'ORDER_CONFIRM_RECEIPT'
				| 'ORDER_CANCEL_LIST' | 'ORDER_CANCEL_CANCELABLES' | 'ORDER_CANCEL_REFUND_INFO' | 'ORDER_CANCEL'
				| 'ORDER_RETURN_LIST' | 'ORDER_RETURN_RETURNABLE' | 'ORDER_RETURN_REFUND_INFO' | 'ORDER_EXCHANGE_ADDITIONAL_PAYMENTS'
				| 'ORDER_RETURN' | 'ORDER_RETURN_CANCEL' | 'ORDER_EXCHANGE_LIST' | 'ORDER_EXCHANGE_EXCHANGEABLE'
				| 'ORDER_EXCHANGE_SWITCH_RETURNABLE' | 'ORDER_EXCHANGE_CANCEL' | 'ORDER_DETAIL' | 'ORDER_CANCEL_DETAIL'
				| 'ORDER_RETURN_DETAIL' | 'ORDER_UPDATE_DELIVERY_ADDRESS_ID' | 'ORDER_RETURN_UPDATE_RETRIEVE_INVOICE' | 'ORDER_EXCHANGE_PREPARE_PAY'
				| 'ORDER_EXCHANGE' | 'ORDER_EXCHANGE_DETAIL' | 'ORDER_EXCHANGE_UPDATE_RETRIEVE_INVOICE' | 'ORDER_UPDATE_DELIVERY_ADDRESS_INFO'
				| 'ORDER_EXCHANGE_PAY_RESULT' | 'ORDER_RECEIPT' | 'ORDER_SEND_RECEIPT_TO_EMAIL' | 'ORDER_EXCHANGE_TO_RETURN'
				| 'ORDER_EXCHANGE_SWITCH_RETURN_REFUND_INFO' | 'ORDER_RETURN_VALIDATE_INVOICE';

/** 주문 */
type orderApiKey = 'ORDER_START' | 'ORDER_BASIC_DATA' | 'ORDER_PREPARE_PAY' | 'ORDER_RESULT'
				| 'ORDER_UTIL_CARD_INSTALLMENTS' | 'ORDER_UTIL_PAYMENT_METHODS' | 'ORDER_UTIL_MY_PAY_METHODS' | 'ORDER_UTIL_MY_PAY_PREPARE_TOKEN'
				| 'ORDER_UTIL_MY_PAY_PREPARE_REIGST' | 'ORDER_UTIL_MY_PAY_MANAGEMENT';

/** 앱 */
type nativeAppApisKey = 'APP_STORE_FIREBASE_MESSAGING_TOKEN' | 'APP_UPDATE_FIREBASE_MESSAGING_TOKEN' | 'APP_IS_RECEIVE_PUSH' | 'APP_UPDATE_PUSH_NOTIFICATION_AGREE'
				| 'APP_INFO' | 'APP_BIOMETRIC_CREATE' | 'APP_BIOMETRIC_LOGIN';

/** 서드파티 */
type thirdPartyApiKey = 'THIRD_PARTY_LOGIN' | 'THIRD_PARTY_PROFILE' | 'THIRD_PARTY_TOKEN' | 'THIRD_PARTY_TOKEN_RESULT'
				| 'THIRD_PARTY_REGIST_USER' | 'THIRD_PARTY_USER_DUPLICATE_CHECK' | 'THIRD_PARTY_USER_CONNECT' | 'THIRD_PARTY_USER_DISCONNECT'
				| 'THIRD_PARTY_IS_TOKEN_PROCESS_COMPLETED';

/** 라이브커머스 */
type liveCommerceApis = 'GENERATE_LIVE_COMMERCE_TOKEN' | 'GET_SCHEDULE_BROAD_CAST' | 'GET_ACTIVE_BROAD_CAST';